package icu.cykuta.beaconshield.config;

import icu.cykuta.beaconshield.BeaconShield;
import org.bukkit.configuration.InvalidConfigurationException;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

public class ConfigFile {

    /**
     * Comment block written once above the first setting generated by a
     * plugin update, so users can tell their original file apart from
     * the generated part.
     */
    private static final List<String> GENERATED_MARKER = List.of(
            "----------------------------------",
            "        Generated Settings",
            "----------------------------------",
            "The settings below were added automatically by a plugin update,",
            "each one with its own explanation. Feel free to move them",
            "anywhere in the file.");

    private PluginConfiguration fileConfiguration;
    private final BeaconShield plugin = BeaconShield.getPlugin();
    private File file;
    private final String fileName;

    public ConfigFile(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Creates the file if it doesn't exist.
     */
    public void register() {
        this.file = new File(plugin.getDataFolder(), fileName);

        if (!this.file.exists()) {
            plugin.saveResource(fileName, false);
        }

        this.fileConfiguration = PluginConfiguration.loadConfiguration(this.file);
        this.matchConfig(this.fileConfiguration, fileName);
    }

    /**
     * Sync the config file with the bundled resource: new keys are copied
     * in (together with their explanation comments) and keys that no
     * longer exist are removed. The first key ever generated this way gets
     * the {@link #GENERATED_MARKER} comment above it, so everything the
     * plugin generates ends up below that marker.
     *
     * @param config The config file.
     * @param fileName The file to match in the resources.
     */
    public void matchConfig(PluginConfiguration config, String fileName) {
        try {
            InputStream is = BeaconShield.getPlugin().getResource(fileName);
            if (is != null) {
                PluginConfiguration defConfig = PluginConfiguration.loadConfiguration(is);
                String firstGeneratedKey = null;

                for (String key : defConfig.getConfigurationSection("").getKeys(true)) {
                    if (!config.contains(key)) {
                        config.set(key, defConfig.get(key));
                        config.setComments(key, defConfig.getComments(key));
                        config.setInlineComments(key, defConfig.getInlineComments(key));

                        // Only root keys land at the bottom of the file,
                        // where the generated section marker belongs.
                        if (firstGeneratedKey == null && !key.contains(".")) {
                            firstGeneratedKey = key;
                        }
                    }
                }

                for (String key : config.getConfigurationSection("").getKeys(true)) {
                    if (!defConfig.contains(key)) {
                        config.set(key, null);
                    }
                }

                if (firstGeneratedKey != null && !this.hasGeneratedMarker(config)) {
                    List<String> comments = new ArrayList<>();
                    comments.add(null); // Blank line separating the user part of the file
                    comments.addAll(GENERATED_MARKER);
                    comments.addAll(config.getComments(firstGeneratedKey));
                    config.setComments(firstGeneratedKey, comments);
                }

                config.save(this.file);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Check if the generated section marker is already written above
     * one of the keys of the file.
     */
    private boolean hasGeneratedMarker(PluginConfiguration config) {
        for (String key : config.getConfigurationSection("").getKeys(false)) {
            if (config.getComments(key).containsAll(GENERATED_MARKER)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Save the file.
     *
     * @throws RuntimeException if an IOException occurs.
     */
    public void save() {
        try {
            this.fileConfiguration.save(this.file);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Reload the file from disk. The file is recreated from the bundled
     * resource if it was deleted, and new default keys are merged in.
     * On error the previous configuration is kept.
     */
    public void reload() {
        try {
            if (!this.file.exists()) {
                plugin.saveResource(fileName, false);
            }

            // load() clears the previous values, so every PluginConfiguration
            // reference held elsewhere sees the new values in place.
            this.fileConfiguration.load(this.file);
            this.matchConfig(this.fileConfiguration, fileName);
        } catch (IOException | InvalidConfigurationException e) {
            plugin.getLogger().severe("Could not reload " + fileName + ": " + e.getMessage());
        }
    }

    public PluginConfiguration getFileConfiguration() {
        return this.fileConfiguration;
    }
}
